"documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "doc/**/*"

"dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "Cargo.toml"

"ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/labeler.yml"
          - ".github/dependabot.yml"

"rust":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*"
          - "tests/**/*"
          - "examples/**/*"
          - "benches/**/*"
          - "build.rs"
          - "Cargo.toml"
          - "Cargo.lock"
          - "rust-toolchain"
          - "rustfmt.toml"
          - ".cargo/**/*"

"JSON":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.json"
