name: JSON check

on:
  push:
    paths:
      - '**.json'
    branches:
      - main
  pull_request:
    paths:
      - '**.json'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
