name: tests

on:
  push:
    paths:
      - '**/*.rs'
      - '**/*.json'
      - 'Cargo.toml'
      - '.github/workflows/tests.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.rs'
      - '**/*.json'
      - 'Cargo.toml'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

env:
  MIDIA_VERSION_POSTFIX: '-tests'
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Install native dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev

      - name: "Checkout code"
        uses: actions/checkout@v5

      - name: "Install Rust toolchain"
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy,rustfmt

      - name: "Set up Just"
        uses: extractions/setup-just@v3

      - name: "Run checks"
        run: just check
