name: tests

on:
  push:
    paths:
      - '**/*.rs'
      - '**/*.json'
      - 'Cargo.toml'
      - '.github/workflows/tests.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.rs'
      - '**/*.json'
      - 'Cargo.toml'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

env:
  MIDIA_VERSION_POSTFIX: '-tests'
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/ci:latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Run checks"
        run: just check
